# Generated by Django 4.0.6 on 2022-09-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_product_id_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
